version: '3'
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_DB}
    volumes:
      - /mnt/newdisk/hexaco/backend:/usr/src/app/backend
      
  database:
    container_name: database
    image: "postgres:latest"
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
