version: '3'
services:
  frontend:
    container_name: frontend
    build: 
      context: ./hexaco-frontend
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    build: 
      context: ./hexaco-backend
    ports:
      - "8085:5000"
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_DB}
      
  database:
    container_name: hexaco-database
    image: "postgres:latest"
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  load-database:
    container_name: load-database
    image: postgres:latest
    volumes:
      - ./hrgpt.sql:/docker-entrypoint-initdb.d/hrgpt.sql
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: ["postgres"]
