"""empty message

Revision ID: 9b8ed176c56d
Revises: 8f28e6d1bd0b
Create Date: 2023-09-18 20:45:00.544346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b8ed176c56d'
down_revision = '8f28e6d1bd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_group_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_category', sa.String(), nullable=False),
    sa.Column('selected_assessment', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['selected_assessment'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_individual_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_category', sa.String(), nullable=False),
    sa.Column('selected_assessment', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('observer_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['observer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['selected_assessment'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scheduled_assessments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selected_assessment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduled_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('assessment_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name='scheduled_assessments_employee_id_fkey'),
    sa.ForeignKeyConstraint(['observer_id'], ['users.id'], name='scheduled_assessments_observer_id_fkey'),
    sa.ForeignKeyConstraint(['selected_assessment'], ['form.id'], name='scheduled_assessments_selected_assessment_fkey'),
    sa.PrimaryKeyConstraint('id', name='scheduled_assessments_pkey')
    )
    op.drop_table('scheduled_individual_assessments')
    op.drop_table('scheduled_group_assessments')
    # ### end Alembic commands ###
