"""empty message

Revision ID: 0f5282b37359
Revises: da4451281321
Create Date: 2023-08-23 01:30:22.731238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5282b37359'
down_revision = 'da4451281321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hexaco_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_nonunique_id', sa.String(), nullable=False),
    sa.Column('Trait', sa.String(), nullable=False),
    sa.Column('Facet', sa.String(), nullable=False),
    sa.Column('Code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fields_field_nonunique_id'), ['field_nonunique_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fields_field_nonunique_id'))

    op.drop_table('hexaco_mapping')
    # ### end Alembic commands ###
