"""empty message

Revision ID: 7ea46f53fc83
Revises: 40ac14228da0
Create Date: 2023-08-27 02:24:32.625906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea46f53fc83'
down_revision = '40ac14228da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['observant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('observant_id')

    # ### end Alembic commands ###
